services:
  client:
    image: nginx:latest
    ports:
      - "3000:80"
  comments:
    image: node:latest
    ports:
      - "4001:4001"

  event-bus:
    image: node:latest
    ports:
      - "4005:4005"
  moderation:
    image: node:latest
    ports:
      - "4003:4003"
  posts:
    image: node:latest
    ports:
      - "4000:4000"
  query:
    image: node:latest
    ports:
      - "4002:4002"