apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
    name: ingress-service
    annotations:
        kubernetes.io/ingress.class: nginx
        nginx.ingress.kubernetes.io/use-regex: "true"
spec:
    rules:
        - host: posts.com # Vous devez ajouter un hôte ici
          http:
              paths:
                  - path: /posts/create
                    pathType: Prefix
                    backend:
                        service:
                            name: posts-service
                            port:
                                number: 4000
                  - path: /posts
                    pathType: Prefix
                    backend:
                        service:
                            name: query-service
                            port:
                                number: 4002
                  - path: /posts/[a-zA-Z0-9]+/comments
                    pathType: Prefix
                    backend:
                        service:
                            name: comments-service
                            port:
                                number: 4001
                  - path: /
                    pathType: Prefix
                    backend:
                        service:
                            name: client-service
                            port:
                                number: 3000
