apiVersion: apps/v1
kind: Deployment
metadata:
    name: moderation-deployment
spec:
    replicas: 1
    selector:
        matchLabels:
            app: moderation
    template:
        metadata:
            name: moderation-pod
            labels:
                app: moderation
        spec:
            containers:
                - name: moderation
                  image: moderation
                  ports:
                      - containerPort: 4003
---
apiVersion: v1
kind: Service
metadata:
    name: moderation-srv
spec:
    type: NodePort
    selector:
        app: moderation
    ports:
        - port: 4003
          targetPort: 4003
