apiVersion: apps/v1
kind: Deployment
metadata:
    name: query-deployment
spec:
    replicas: 1
    selector:
        matchLabels:
            app: query
    template:
        metadata:
            name: query-pod
            labels:
                app: query
        spec:
            containers:
                - name: query
                  image: query
                  imagePullPolicy: Never
                  ports:
                      - containerPort: 4002
---
apiVersion: v1
kind: Service
metadata:
    name: query-srv
spec:
    type: NodePort
    selector:
        app: query
    ports:
        - port: 4002
          targetPort: 4002
